version: '3'

services:
  pipeline:
    image: registry.gitlab.uni-oldenburg.de/ebki3136/mediaktionsplan-pipeline
    volumes:
      - /home/jonas/Studium/Arztbriefe/:/io/data
      - ./debug:/io/debug
      - ./logs:/io/logs
    environment:
      OPENEHR_URL: http://10.18.0.119:8080/ehrbase/
      DEBUG_DRAWIMAGES: false
      LOGGING_LEVEL_COM_JAYPI4C_BA_PIPELINE_MEDICATIONPLAN: INFO
      VALIDATION_ACTIVE: false