name: tinia
services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: ..
    depends_on:
      - backend
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      TINIA_SECURITY_ALLOWED_ORIGINS: "http://localhost"
    depends_on:
      - redis
      - rabbitmq
  extractor:
    build:
      context: ..
      dockerfile: extractor/Dockerfile
    depends_on:
      - backend
      - rabbitmq
#  extractor2:
#    build:
#      context: ..
#      dockerfile: extractor/Dockerfile
#    depends_on:
#      - backend
#      - rabbitmq
  openehr:
    build:
      context: ..
      dockerfile: openehr/Dockerfile
    depends_on:
       - backend
       - rabbitmq

  ehrbase:
    image: ehrbase/ehrbase:2.32.0
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
      SERVER_NODENAME: local.ehrbase.org
      SPRING_PROFILES_ACTICE: local
    depends_on:
      - ehrdb
  ehrdb:
    image: ehrbase/ehrbase-v2-postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASS_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASS: ehrbase_restricted

  ingress:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:7.4
  rabbitmq:
    image: rabbitmq:3
