events {
    worker_connections 1024;
}

http {
    upstream apihosts {
        server backend:8081;
        keepalive 64;
    }


    upstream frontends {
        server frontend:8080;
        keepalive 64;
    }

    upstream ehrbases {
        server ehrbase:8080;
        keepalive 64;
    }

    server {
        listen       80;
        tcp_nodelay on; # improve latency for small packets

        # DNS resolver needed for Docker
        resolver 127.0.0.11 valid=10s;

       location / {
           proxy_pass http://frontends;
           proxy_http_version 1.1;
           proxy_set_header Connection '';
       }

        location ~ ^/(api|swagger-ui|v3)/ {
            client_max_body_size 100M;
            proxy_pass http://apihosts;
            proxy_http_version 1.1;
            proxy_set_header Connection '';
        }

        location /ehrbase {
            client_max_body_size 100M;
            proxy_pass http://ehrbases;
            proxy_http_version 1.1;
            proxy_set_header Connection '';
        }

    }
}